import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConfigProvider from "@/context/ConfigProvider";
import NotificationProvider from "@/context/NotificationProvider";
import ApiStatusProvider from "@/context/ApiStatusProvider";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <ConfigProvider>
          <ApiStatusProvider>
            <NotificationProvider>
              <div className="flex min-h-screen bg-gray-50">
                <Sidebar />
                <div className="flex flex-col flex-1 h-screen">
                  {/* <header className="h-16 bg-[#18191a] flex items-center px-8 shadow-lg">
                    <h1 className="text-2xl font-bold text-white tracking-tight">PriceNotifier Dashboard</h1>
                  </header> */}
                  <main className="flex-1 p-10 bg-gray-50">
                    {children}
                  </main>
                </div>
              </div>
            </NotificationProvider>
          </ApiStatusProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
